### ISSUE TITLE
Contextが空っぽになる

### ISSUE THREAD

**Issue by nyatinte** [ycu-engine/ds-club-site#154]
### 質問の内容

リゾルバのContextが空になってしまいます

おそらく原因は以下のものです
```
[0] FirebaseAuthError: The Firebase ID token has been revoked.
[0]     at /workspace/node_modules/firebase-admin/lib/auth/base-auth.js:973:27
[0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0]     at verifyToken (/workspace/services/backend/src/modules/auth/index.ts:5:26)
[0]     at ApolloServer.createContext [as context] (/workspace/services/backend/src/context.ts:22:24)
[0]     at ApolloServer.graphQLServerOptions (/workspace/node_modules/apollo-server-core/src/ApolloServer.ts:947:13)
[0]     at resolveGraphqlOptions (/workspace/node_modules/apollo-server-core/src/graphqlOptions.ts:95:12)
[0]     at runHttpQuery (/workspace/node_modules/apollo-server-core/src/runHttpQuery.ts:216:15) {
[0]   errorInfo: {
[0]     code: 'auth/id-token-revoked',
[0]     message: 'The Firebase ID token has been revoked.'
[0]   },
[0]   codePrefix: 'auth'
[0] }
```

[Admin Authentication API エラー | Firebase - Googlehttps://firebase.google.com › auth › admin › errors](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiEre2jv836AhXetlYBHTPABM4QFnoECA0QAQ&url=https%3A%2F%2Ffirebase.google.com%2Fdocs%2Fauth%2Fadmin%2Ferrors%3Fhl%3Dja&usg=AOvVaw1SbFr4kRCx1TFD_lkm607j)も参照したのですが、解決策がわからないので教えていただきたいです。

### スクリーンショットや該当のコード

```
[0] FirebaseAuthError: The Firebase ID token has been revoked.
[0]     at /workspace/node_modules/firebase-admin/lib/auth/base-auth.js:973:27
[0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0]     at verifyToken (/workspace/services/backend/src/modules/auth/index.ts:5:26)
[0]     at ApolloServer.createContext [as context] (/workspace/services/backend/src/context.ts:22:24)
[0]     at ApolloServer.graphQLServerOptions (/workspace/node_modules/apollo-server-core/src/ApolloServer.ts:947:13)
[0]     at resolveGraphqlOptions (/workspace/node_modules/apollo-server-core/src/graphqlOptions.ts:95:12)
[0]     at runHttpQuery (/workspace/node_modules/apollo-server-core/src/runHttpQuery.ts:216:15) {
[0]   errorInfo: {
[0]     code: 'auth/id-token-revoked',
[0]     message: 'The Firebase ID token has been revoked.'
[0]   },
[0]   codePrefix: 'auth'
[0] }
```

### 参考にした資料など

- [Admin Authentication API エラー | Firebase - Googlehttps://firebase.google.com › auth › admin › errors](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiEre2jv836AhXetlYBHTPABM4QFnoECA0QAQ&url=https%3A%2F%2Ffirebase.google.com%2Fdocs%2Fauth%2Fadmin%2Ferrors%3Fhl%3Dja&usg=AOvVaw1SbFr4kRCx1TFD_lkm607j)
- [[Firebase Authentication]IDトークンをRevokeさせない ... - Qiitahttps://qiita.com › Go](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjxhNC9wM36AhUGgFYBHc4TBs4QFnoECB8QAQ&url=https%3A%2F%2Fqiita.com%2Fchan-koh%2Fitems%2Fd69daff4d947502a2e48&usg=AOvVaw1heC8N1giB3zXRkQWPSxt7)

**Comment by YutaUra** [comment]
多分だけど、この辺の問題かなって思います！
https://github.com/ycu-engine/ds-club-site/blob/8efaa7eee969f23ee5de9a81b71181e7f675bf61/services/frontend/src/clients/apollo.ts#L10-L26

getIdToken で生成した idToken が revoked なものになっちゃってるかも？

一応、クライアント側で再度認証を行なって idToken を生成すれば解決するかなとは思う
https://firebase.google.com/docs/auth/admin/manage-sessions?hl=ja#respond_to_token_revocation_on_the_client


けど、そもそもなんで revoled されたんだろう。その現象って頻出する？もしたまーになっちゃうとかだったら対応せずがよいかも

**Comment by nyatinte** [comment]
@YutaUra 
クライアント側で再度認証ということはログインし直すということですか？
再ログインでは解決しませんでした。
それと、idTokenがずっと同じ値なんですけどここら辺だったりします？

**Comment by nyatinte** [comment]
https://github.com/ycu-engine/ds-club-site/blob/8efaa7eee969f23ee5de9a81b71181e7f675bf61/services/frontend/src/clients/apollo.ts#L10-L26

これを

```diff
 const authLink = setContext(async (_, { headers }) => { 
   if (!auth.currentUser) { 
     return { headers } 
   } 

   try { 
     const idToken = await getIdToken(auth.currentUser, true) 
+     const credential = EmailAuthProvider.credential(
+     'メアド',
+     'パスワード',
+     )
+    await reauthenticateWithCredential(auth.currentUser, credential)
     return { 
       headers: { 
         ...headers, 
         Authorization: idToken ? `Bearer ${idToken}` : '', 
       }, 
     } 
```

にして一回実行すると治ったかも
